/** 
 * Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * 
 * Licensed under the Amazon Software License (the "License"). You may not
 * use this file except in compliance with the License. A copy of the License
 *  is located at
 * 
 *       http://aws.amazon.com/asl/  
 *        
 * This Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */

#ifndef _MUD_WINDOWS_UTIL_H_
#define _MUD_WINDOWS_UTIL_H_

#define _WINSOCKAPI_
#include <windows.h>

#include "AmazonCompositeResult/SimpleResultCodes.h"

namespace mud
{

#define WSERROR_TO_SIMPLE_RESULT_CODE( wsError, simpleResultCode ) case (wsError): {return simpleResultCode;}

/**
 *  Windows utility class.
 */
class WindowsUtil
{
public:
    /** Convert the Windows system error code to Simple Result Code. */
    static uint32_t systemErrorCodeToSimpleResultCode( DWORD systemErrorCode )
    {
        return systemErrorCode | SIMPLE_RESULT_WINDOWS_SYSTEM_CODE_START;
    }

    /** Convert the Winsock error to Simple Result Code. */
    static uint32_t wsErrorToSimpleResultCode( int wsError)
    {
        uint32_t retVal = SIMPLE_RESULT_NET_UNKNOWN;

        switch (wsError)
        {
            WSERROR_TO_SIMPLE_RESULT_CODE( WSANOTINITIALISED, SIMPLE_RESULT_NOT_INITIALIZED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAENETDOWN, SIMPLE_RESULT_NET_NETWORK_DOWN )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEAFNOSUPPORT, SIMPLE_RESULT_NET_AF_NOT_SUPPORTED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEINPROGRESS, SIMPLE_RESULT_IN_PROGRESS )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEMFILE, SIMPLE_RESULT_NO_FD )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEINVAL, SIMPLE_RESULT_INVALID )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAENOBUFS, SIMPLE_RESULT_NO_MEMORY )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEPROTONOSUPPORT, SIMPLE_RESULT_NET_PROTO_NOT_SUPPORTED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEPROTOTYPE, SIMPLE_RESULT_NET_PROTO_TYPE_WRONG )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEACCES, SIMPLE_RESULT_PERMISSION_ERROR )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEADDRINUSE, SIMPLE_RESULT_NET_ADDR_IN_USE )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEADDRNOTAVAIL, SIMPLE_RESULT_NET_ADDR_NOT_AVAILABLE )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEFAULT, SIMPLE_RESULT_FAULT )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAENOTSOCK, SIMPLE_RESULT_NET_NOT_SOCKET )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEISCONN, SIMPLE_RESULT_NET_SOCKET_ALREADY_CONNECTED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEOPNOTSUPP, SIMPLE_RESULT_NOT_SUPPORTED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAECONNRESET, SIMPLE_RESULT_NET_CONN_RESET )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEINTR, SIMPLE_RESULT_INTERRUPTED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEWOULDBLOCK, SIMPLE_RESULT_AGAIN )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEALREADY, SIMPLE_RESULT_ALREADY )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAECONNREFUSED, SIMPLE_RESULT_NET_CONN_REFUSED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAENETUNREACH, SIMPLE_RESULT_NET_NETWORK_UNREACHABLE )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEHOSTUNREACH, SIMPLE_RESULT_NET_HOST_UNREACHABLE )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAETIMEDOUT, SIMPLE_RESULT_TIMEOUT )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAENETRESET, SIMPLE_RESULT_NET_NETWORK_RESET )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAENOTCONN, SIMPLE_RESULT_NET_SOCKET_NOT_CONNECTED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAESHUTDOWN, SIMPLE_RESULT_NET_SOCKET_SHUTDOWN )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEMSGSIZE, SIMPLE_RESULT_MSG_SIZE_ERROR )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAECONNABORTED, SIMPLE_RESULT_NET_CONN_ABORTED )
            WSERROR_TO_SIMPLE_RESULT_CODE( WSAEDESTADDRREQ, SIMPLE_RESULT_NET_DEST_ADDR_REQUIRED )

            default:
                retVal = SIMPLE_RESULT_NET_UNKNOWN;
                break;

        }

        return retVal;
    }
};

} //namespace mud

#endif //_MUD_WINDOWSUTILL_H_

