/** 
 * Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * 
 * Licensed under the Amazon Software License (the "License"). You may not
 * use this file except in compliance with the License. A copy of the License
 *  is located at
 * 
 *       http://aws.amazon.com/asl/  
 *        
 * This Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */

#include "SimpleResultCodes.h"

namespace acr
{

#define CONVERT_RESULT_CODE_TO_NAME( resultCode ) case (resultCode): {return #resultCode;}

/** Get the string representation of a code. */
const char* getSimpleResultCodeName( uint32_t code )
{
    if ((code >= SIMPLE_RESULT_WINDOWS_SYSTEM_CODE_START)
        && (code <= SIMPLE_RESULT_WINDOWS_SYSTEM_CODE_END))
    {
        return "Windows system error code";
    }

    switch (code)
    {
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_OK )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_UNKNOWN )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_INVALID )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_FAULT )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_PERMISSION_ERROR )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NO_MEMORY )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_BAD_FD )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NO_FD )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_OUT_OF_BOUND )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_TIMEOUT )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_AGAIN )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_BUSY )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_ABORTED ) 
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_INTERRUPTED ) 
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NOT_FOUND ) 
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_DUPLICATED ) 
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NOT_SUPPORTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_IN_PROGRESS )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_ALREADY )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_PENDING )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_DEAD_LOCK )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NOT_INITIALIZED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_ALREADY_INITIALIZED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NOT_DEINITIALIZED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_ALREADY_DEINITIALIZED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NOT_STARTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_ALREADY_STARTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NOT_STOPPED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_ALREADY_STOPPED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NOT_RUNNING )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_ALREADY_RUNNING )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_BAD_FILE )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_BAD_DIR )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_MSG_SIZE_ERROR )

        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_THREAD_UNKNOWN )

        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_UNKNOWN )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_AF_NOT_SUPPORTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_PROTO_NOT_SUPPORTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_NOT_SOCKET )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_ADDR_IN_USE )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_ADDR_NOT_AVAILABLE )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_CONN_ABORTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_PROTO_ERROR )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_SOCKET_TYPE_NOT_SUPPORTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_CONN_REFUSED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_CONN_RESET )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_SOCKET_ALREADY_CONNECTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_SOCKET_NOT_CONNECTED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_NETWORK_UNREACHABLE )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_HOST_UNREACHABLE )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_DEST_ADDR_REQUIRED )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_NETWORK_RESET )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_NETWORK_DOWN )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_PROTO_TYPE_WRONG )
        CONVERT_RESULT_CODE_TO_NAME( SIMPLE_RESULT_NET_SOCKET_SHUTDOWN )

        default:
            return "SIMPLE_RESULT_UNKNOWN";
    }

    return "SIMPLE_RESULT_UNKNOWN";
}

}

